// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_tiyXbw80BuMefl8naCIV5OaIbnaZKU',
    appId: '1:607334976112:web:3a5b1a1cb01be5cd8e42b5',
    messagingSenderId: '607334976112',
    projectId: 'whatsapp-ede0f',
    authDomain: 'whatsapp-ede0f.firebaseapp.com',
    storageBucket: 'whatsapp-ede0f.appspot.com',
    measurementId: 'G-QM0L8Z3TEG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOMBPEFrgtetU6c4bLiFF5a6yckDZfm8',
    appId: '1:607334976112:ios:1539c28b650aa26a8e42b5',
    messagingSenderId: '607334976112',
    projectId: 'whatsapp-ede0f',
    storageBucket: 'whatsapp-ede0f.appspot.com',
    iosBundleId: 'com.haider.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn_tiyXbw80BuMefl8naCIV5OaIbnaZKU',
    appId: '1:607334976112:web:1fbc733fd927c8b18e42b5',
    messagingSenderId: '607334976112',
    projectId: 'whatsapp-ede0f',
    authDomain: 'whatsapp-ede0f.firebaseapp.com',
    storageBucket: 'whatsapp-ede0f.appspot.com',
    measurementId: 'G-FQZGP0QQ2N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOMBPEFrgtetU6c4bLiFF5a6yckDZfm8',
    appId: '1:607334976112:ios:1539c28b650aa26a8e42b5',
    messagingSenderId: '607334976112',
    projectId: 'whatsapp-ede0f',
    storageBucket: 'whatsapp-ede0f.appspot.com',
    iosBundleId: 'com.haider.whatsapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrkOLdvMznJYJlKYFaY8ZmobdIpPT2uo',
    appId: '1:607334976112:android:31d309d796623b6e8e42b5',
    messagingSenderId: '607334976112',
    projectId: 'whatsapp-ede0f',
    storageBucket: 'whatsapp-ede0f.appspot.com',
  );

}